Repository bcgov/quickstart-openshift, pull requests merged in 2022-04, with the labels that each got.

#206 Clean up old packages from ghcr.io
  .github/workflows/pr-close.yml
Labels: enhancement

#211 Feat/streamline pipeline
  .github/example_workflows/issue-todo.yml
  .github/example_workflows/issue-triage.yml
  .github/graphics/pr.png
  .github/workflows/main.yml
  .github/workflows/pr-open.yml
Labels: enhancement

#214 Envars for finding backend, database
  .github/pipeline/deploy.backend.yml
  .github/pipeline/deploy.frontend.yml
Labels: enhancement

#216 Feat/compose
  .gitignore
  docker-compose.yml
Labels: enhancement

#217 Feat/prod
  .github/pipeline/deploy.backend.yml
  .github/pipeline/deploy.database.yml
  .github/pipeline/deploy.frontend.yml
  .github/workflows/pr-open.yml
Labels: enhancement

#230 Update pipeline pics in readme
  .github/graphics/main-merge.png
  .github/graphics/pr-cleanup.png
  .github/graphics/pr-open.png
  .github/graphics/pr.png
  .github/workflows/main.yml
  README.md
Labels: documentation

#232 Docs/updates
  .github/workflows/pr-open.yml
  README.md
Labels: documentation

#233 Merge #220: Populate dev database
  .github/pipeline/deploy.backend.yml
  .github/pipeline/deploy.database.yml
  backend/package-lock.json
  backend/package.json
  backend/src/app.module.ts
  backend/src/app.service.ts
  backend/src/main.ts
  backend/src/user/entities/user.entity.ts
  backend/src/user/user.controller.spec.ts
  backend/src/user/user.controller.ts
  backend/src/user/user.module.ts
  backend/src/user/user.service.spec.ts
  backend/src/user/user.service.ts
  backend/src/users/dto/create-user.dto.ts
  backend/src/users/dto/update-user.dto.ts
  backend/src/users/dto/user.dto.ts
  backend/src/users/entities/users.entity.ts
  backend/src/users/users.controller.spec.ts
  backend/src/users/users.controller.ts
  backend/src/users/users.module.ts
  backend/src/users/users.service.spec.ts
  backend/src/users/users.service.ts
  docker-compose.yml
Labels: enhancement

#240 Var consistency
  .github/pipeline/deploy.backend.yml
  docker-compose.yml
Labels: enhancement

#239 Feat/main trivy
  .github/workflows/main.yml
  .github/workflows/pr-close.yml
Labels: enhancement

#241 Feat/prod pod cleanup
  .github/workflows/merge-main.yml
Labels: enhancement

#246 Reduce build steps and time
  backend/Dockerfile
  frontend/Dockerfile
Labels: enhancement

#257 Simplify docker compose mounts/binds
  docker-compose.yml
Labels: enhancement

#256 Use consistent vars for Postgres
  .github/pipeline/deploy.backend.yml
  .github/pipeline/deploy.database.yml
  backend/src/app.module.ts
  docker-compose.yml
Labels: bug

#259 Optional OpenShift network policies
  .github/openshift/deploy.backend.yml
  .github/openshift/deploy.database.yml
  .github/openshift/deploy.frontend.yml
  .github/openshift/networkPolicies.yml
  .github/workflows/pr-open.yml
  README.md
Labels: enhancement

#260 Update README for network policies
  README.md
Labels: documentation

#261 Limit Snyk to main merge only, too much use for free plan
  .github/workflows/pr-open.yml
  README.md
Labels: bug

#268 Pod cleanup only runs if there are pods to clean up
  .github/workflows/merge-main.yml
Labels: bug
