Repository bcgov/quickstart-openshift, pull requests merged in 2022-12, with the labels that each got.

#665 Rename LICENSE.md -> LICENSE, repo-mountie nags
  LICENSE
Labels: documentation

#667 Moved Trivy from merge to test/analyse workflow
  .github/workflows/merge-main.yml
  .github/workflows/unit-tests.yml
Labels: enhancement

#669 Removed trivy prereq in main-merge.yml
  .github/workflows/merge-main.yml
Labels: bug

#699 Add vu3 starter template
  frontend/.eslintrc.cjs
  frontend/.gitignore
  frontend/.prettierrc.json
  frontend/.vscode/extensions.json
  frontend/Caddyfile
  frontend/Dockerfile
  frontend/README.md
  frontend/env.d.ts
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.js
  frontend/public/favicon.ico
  frontend/src/App.vue
  frontend/src/app.controller.spec.ts
  frontend/src/app.controller.ts
  frontend/src/app.module.ts
  frontend/src/app.service.ts
  frontend/src/assets/base.css
  frontend/src/assets/bc-gov-logo.svg
  frontend/src/assets/main.css
  frontend/src/components/HelloWorld.vue
  frontend/src/components/__tests__/HelloWorld.spec.ts
  frontend/src/layouts/MainLayout.vue
  frontend/src/main.ts
  frontend/src/quasar-variables.sass
  frontend/src/router/index.ts
  frontend/src/router/routes.ts
  frontend/src/stores/counter.ts
  frontend/src/views/AboutView.vue
  frontend/tailwind.config.js
  frontend/tsconfig.app.json
  frontend/tsconfig.config.json
  frontend/tsconfig.json
  frontend/tsconfig.vitest.json
  frontend/vite.config.ts
  frontend/vitest.config.ts
Labels: enhancement
