Repository bcgov/quickstart-openshift, pull requests merged in 2023-06, with the labels that each got.

#1174 Upgrade to latest version for merge to main workflow.
  .github/workflows/merge-main.yml
Labels: bug

#1201 bug fixes for findone endpoint
  backend/src/users/users.controller.ts
  backend/src/users/users.service.spec.ts
  backend/src/users/users.service.ts
Labels: bug

#1206 fix sequence and update method from patch to put
  backend/db/migrations/V1.0.1__alter_user_seq.sql
  backend/src/users/users.controller.ts
Labels: bug

#1210 Added the mapping from DB obect to Struct
  backend-python/src/v1/routes/user_routes.py
Labels: bug

#1217 code changes for integration tests
  .github/workflows/merge-main.yml
  backend-go/src/v1/routes/user-routes.go
  backend-go/src/v1/services/user-service.go
  integration-tests/package-lock.json
  integration-tests/package.json
  integration-tests/src/main.js
  integration-tests/src/test_suites/it.backend.fastapi.json
  integration-tests/src/test_suites/it.backend.fiber.json
  integration-tests/src/test_suites/it.backend.nest.json
  integration-tests/src/test_suites/it.backend.quarkus.json
Labels: enhancement

#1219 bug fixes for integration testing
  backend-go/src/app.go
  backend-java/src/main/resources/application.properties
  backend-python/src/v1/routes/user_routes.py
  backend/db/migrations/V1.0.1__alter_user_seq.sql
  docker-compose.go.yml
  integration-tests/src/main.js
  integration-tests/src/test_suites/it.backend.fastapi.json
  integration-tests/src/test_suites/it.backend.fiber.json
  integration-tests/src/test_suites/it.backend.quarkus.json
Labels: bug

#1223 feat: consolidate docker compose files
  .github/workflows/merge-main.yml
  .gitignore
  backend-go/openshift.deploy.yml
  backend-go/src/database/connections.go
  backend-java/mvnw
  backend-java/openshift.deploy.yml
  backend-java/src/main/resources/application.properties
  backend-python/generate-models.sh
  backend-python/openshift.deploy.yml
  backend-python/run-unit-tests.sh
  backend-python/src/core/config.py
  backend-python/start-local.sh
  backend/openshift.deploy.yml
  backend/package-lock.json
  backend/src/app.module.ts
  database/openshift.deploy.yml
  database/templates/openshift.backups.yml
  docker-compose.go.yml
  docker-compose.java.yml
  docker-compose.py.yml
  docker-compose.yml
  frontend/vite.config.ts
Labels: enhancement

#1225 Bug/docker healthchecks
  docker-compose.yml
Labels: bug

#1227 Readme - mention podman, simplify pluggable backends
  README.md
Labels: documentation

#1234 Contributing: recommend branches over forks
  CONTRIBUTING.md
Labels: documentation

#1236 PR deployment triggers for db
  .github/workflows/pr-open.yml
Labels: bug

#1238 Caddy update and OpenShift security context
  frontend/Caddyfile
  frontend/Dockerfile
  frontend/openshift.deploy.yml
Labels: enhancement, dependencies
