Repository bcgov/quickstart-openshift, pull requests merged in 2023-10, with the labels that each got.

#1449 feat: workflow cleanup and simplifications
  .github/dependabot.yml
  .github/workflows/merge.yml
  .github/workflows/pr-open.yml
  README.md
  backend/openshift.deploy.yml
  database/openshift.deploy.yml
  frontend/openshift.deploy.yml
Labels: enhancement

#1461 Feat/cleanup ii
  .github/workflows/merge.yml
Labels: bug, enhancement

#1463 feat: scheduled penetration tests
  .github/workflows/merge.yml
  .github/workflows/pentests.yml
  .github/workflows/pr-open.yml
Labels: enhancement

#1464 bug: workflow fixes
  .github/workflows/merge.yml
  .github/workflows/scheduled.yml
Labels: bug

#1465 ci: move SchemaSpy and PenTests into scheduled.yml
  .github/workflows/merge.yml
  .github/workflows/scheduled.yml
Labels: enhancement

#1466 bug: promote migrations
  .github/workflows/merge.yml
Labels: bug

#1475 Revert "1454 implement helm"
  .github/workflows/merge.yml
  .github/workflows/pr-open.yml
  charts/quickstart-openshift/Chart.yaml
  charts/quickstart-openshift/charts/component/.helmignore
  charts/quickstart-openshift/charts/component/templates/_helpers.tpl
  charts/quickstart-openshift/charts/component/templates/configmap.yaml
  charts/quickstart-openshift/charts/component/templates/deployment.yaml
  charts/quickstart-openshift/charts/component/templates/hpa.yaml
  charts/quickstart-openshift/charts/component/templates/imagestreams.yaml
  charts/quickstart-openshift/charts/component/templates/ingress.yaml
  charts/quickstart-openshift/charts/component/templates/route.yaml
  charts/quickstart-openshift/charts/component/templates/service.yaml
  charts/quickstart-openshift/charts/component/templates/serviceaccount.yaml
  charts/quickstart-openshift/charts/crunchy-postgres/Chart.yaml
  charts/quickstart-openshift/charts/crunchy-postgres/templates/PostgresCluster.yaml
  charts/quickstart-openshift/templates/_helpers.tpl
  charts/quickstart-openshift/templates/knp.yaml
  charts/quickstart-openshift/templates/secret.yaml
  charts/quickstart-openshift/values-pr.yaml
  charts/quickstart-openshift/values.yaml
  database/charts/.helmignore
  database/charts/Chart.yaml
  database/charts/templates/NOTES.txt
  database/charts/templates/_helpers.tpl
  database/charts/templates/backups.yaml
  database/charts/templates/database.yaml
  database/charts/templates/secret.yaml
  database/charts/values.schema.json
  database/charts/values.yaml
Labels: bug

#1478 deps: msw
  frontend/package-lock.json
  frontend/package.json
Labels: dependencies

#1488 feat: snyk warnings
  frontend/package-lock.json
  frontend/package.json
Labels: dependencies

#1480 feat: helm
  .github/workflows/merge.yml
  .github/workflows/pr-close.yml
  .github/workflows/pr-open.yml
  charts/quickstart-openshift-helm/.helmignore
  charts/quickstart-openshift-helm/Chart.yaml
  charts/quickstart-openshift-helm/templates/_helpers.tpl
  charts/quickstart-openshift-helm/templates/knp.yaml
  charts/quickstart-openshift-helm/templates/secret.yaml
  charts/quickstart-openshift-helm/values-pr.yaml
  charts/quickstart-openshift-helm/values.yaml
  database/Dockerfile
  database/charts/templates/NOTES.txt
  database/charts/templates/_helpers.tpl
  database/charts/templates/backups.yaml
  database/charts/templates/database.yaml
  database/charts/templates/secret.yaml
  database/charts/values.schema.json
  database/charts/values.yaml
  database/openshift.deploy.yml
  database/postgis/Dockerfile
Labels: enhancement

#1494 feat: age out Pull Request environments
  .github/workflows/pr-purge.yml
Labels: enhancement

#1502 chore(deps): bump dependencies in backend
  backend/package-lock.json
  backend/package.json
Labels: dependencies

#1504 feat: enforce conventional commits
  .github/workflows/pr-open.yml
Labels: enhancement

#1505 ci: tag instead of release after PROD deploy
  .github/workflows/merge.yml
Labels: enhancement

#1506 ci: workflow cleanup
  .github/workflows/merge.yml
  .github/workflows/pr-close.yml
  .github/workflows/pr-open.yml
  .github/workflows/pr-purge.yml
  .github/workflows/scheduled.yml
Labels: enhancement

#1510 fix: tagging
  .github/workflows/merge.yml
  .github/workflows/pr-close.yml
  .github/workflows/pr-open.yml
  .github/workflows/scheduled.yml
  backend/db/Dockerfile
  docker-compose.yml
  migrations/Dockerfile
  migrations/sql/V1.0.0__init.sql
  migrations/sql/V1.0.1__alter_user_seq.sql
Labels: bug

#1517 fix: helm collisions
  .github/workflows/.deploy.yml
  .github/workflows/merge.yml
  charts/quickstart-openshift/Chart.lock
Labels: bug

#1525 fix: postgres and flyway version mismatch
  charts/quickstart-openshift/values-pr.yaml
  charts/quickstart-openshift/values.yaml
Labels: bug

#1523 ci: tagging
  .github/workflows/pr-close.yml
  .github/workflows/pr-open.yml
  frontend/Dockerfile
Labels: enhancement

#1529 fix: merge workflow dependencies
  .github/workflows/merge.yml
Labels: bug

#1496 feat: delete Helm PR releases older than a week
  .github/workflows/pr-close.yml
  .github/workflows/scheduled.yml
Labels: enhancement

#1547 fix: cleanup step to remove Bitnami Crunchy PVCs
  .github/workflows/pr-close.yml
Labels: enhancement

#1550 fix: make everything read from global secret.
  .github/workflows/.deploy.yml
  charts/quickstart-openshift/templates/secret.yaml
  charts/quickstart-openshift/values-pr.yaml
Labels: bug

#1553 fix: fix POSTGIS extension with correct script.
  charts/quickstart-openshift/values-pr.yaml
  charts/quickstart-openshift/values.yaml
Labels: bug

#1556 feat: extend Renovate config from bcgov/nr-renovate
  renovate.json
Labels: enhancement, dependencies

#1558 chore: update Renovate repo
  renovate.json
Labels: dependencies

#1532 chore(deps): update dependency msw to v2
  frontend/.eslintrc.yml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/test-setup.ts
Labels: dependencies
