Repository bcgov/quickstart-openshift, pull requests merged in 2023-09, with the labels that each got.

#1309 Feat/cleanup code ql
  .github/workflows/analysis.yml
  .github/workflows/merge-main.yml
  .github/workflows/pr-close.yml
  .github/workflows/pr-open.yml
  .github/workflows/tests.yml
  .github/workflows/unit-tests.yml
  backend-go/Dockerfile
Labels: enhancement

#1338 [Snyk] Security upgrade cypress from 12.15.0 to 12.17.4 (was 13)
  frontend/package-lock.json
  frontend/package.json
Labels: dependencies

#1348 feat: reduce python surface and image size
  backend-python/Dockerfile
  backend-python/poetry.lock
  backend-python/start-openshift.sh
Labels: enhancement, dependencies

#1352 feat: new cleanup action
  .github/workflows/merge-main.yml
Labels: enhancement

#1353 Misc corrections
  .github/workflows/analysis.yml
  .github/workflows/merge-main.yml
  .github/workflows/pr-close.yml
  .github/workflows/pr-open.yml
  .github/workflows/tests.yml
  README.md
  backend-go/db/Dockerfile
  backend-py/.prospector.yaml
  backend-py/Dockerfile
  backend-py/README.md
  backend-py/db/Dockerfile
  backend-py/db/migrations/V1.0.0__init.sql
  backend-py/generate-models.sh
  backend-py/logger.conf
  backend-py/openshift.deploy.yml
  backend-py/poetry.lock
  backend-py/pyproject.toml
  backend-py/run-unit-tests.sh
  backend-py/src/__init__.py
  backend-py/src/core/__init__.py
  backend-py/src/core/config.py
  backend-py/src/db/__init__.py
  backend-py/src/db/session.py
  backend-py/src/main.py
  backend-py/src/v1/__init__.py
  backend-py/src/v1/models/__init__.py
  backend-py/src/v1/models/entities.py
  backend-py/src/v1/models/model.py
  backend-py/src/v1/repository/__init__.py
  backend-py/src/v1/repository/repository.py
  backend-py/src/v1/repository/user_repository.py
  backend-py/src/v1/routes/__init__.py
  backend-py/src/v1/routes/user_routes.py
  backend-py/src/v1/structs/__init__.py
  backend-py/src/v1/structs/user.py
  backend-py/start-local.sh
  backend-py/test/test_main.py
  backend/db/Dockerfile
  backend/openshift.deploy.yml
  database/Dockerfile
  database/postgis/Dockerfile
  docker-compose.yml
  frontend/openshift.deploy.yml
Labels: bug, documentation, enhancement

#1355 feat: node consistency
  .github/workflows/merge-main.yml
  backend/Dockerfile
  database/Dockerfile
  database/postgis/Dockerfile
  frontend/Dockerfile
  frontend/package-lock.json
  frontend/package.json
Labels: enhancement

#1365 deps: bump builder action
  .github/workflows/pr-open.yml
Labels: dependencies

#1375 feat: quote inputs
  .github/workflows/merge-main.yml
  backend-go/openshift.deploy.yml
  backend-java/openshift.deploy.yml
  backend-py/openshift.deploy.yml
  backend/openshift.deploy.yml
  common/openshift.init.yml
  database/openshift.deploy.yml
  frontend/openshift.deploy.yml
Labels: enhancement

#1380 bug: dial back Quarkus to 3.2.4.Final
  backend-java/pom.xml
Labels: bug, dependencies

#1386 deps: bump PR description action
  .github/workflows/pr-open.yml
Labels: dependencies

#1393 chore: comment out schemaspy until fixed
  .github/workflows/merge-main.yml
Labels: bug

#1395 Update merge-main.yml
  .github/workflows/merge-main.yml
Labels: bug

#1396 chore: indentation
  .github/workflows/merge-main.yml
Labels: bug

#1398 feat: speed up code ql java
  .github/workflows/analysis.yml
Labels: enhancement

#1388 feat: adjust node and caddy, align with caddy defaults
  backend/Dockerfile
  frontend/Caddyfile
  frontend/Dockerfile
Labels: enhancement

#1419 bug: ZAP issue duplication
  .github/workflows/merge-main.yml
Labels: bug

#1422 feat: roll init into database
  .github/workflows/merge.yml
  .github/workflows/pr-open.yml
  .graphics/branch-protection.png
  .graphics/deploymentUpdate.png
  .graphics/main-merge.png
  .graphics/merge-main.png
  .graphics/mergeNotification.png
  .graphics/packages.png
  .graphics/pr-cleanup.png
  .graphics/pr-close.png
  .graphics/pr-open.png
  .graphics/template.png
  .graphics/unit-tests.png
  README.md
  common/charts/.helmignore
  common/charts/Chart.yaml
  common/charts/templates/NOTES.txt
  common/charts/templates/_helpers.tpl
  common/charts/values.schema.json
  common/charts/values.yaml
  common/openshift.init.yml
  database/charts/templates/secret.yaml
  database/openshift.deploy.yml
Labels: enhancement

#1423 feat: add caddy to docker-compose
  docker-compose.yml
  frontend/index.html
Labels: enhancement

#1335 Update README.md
  .github/SchemaSpy_GH.png
  .github/workflows/analysis.yml
  .github/workflows/merge.yml
  .graphics/analysis.yml.png
  .graphics/main-merge.png
  .graphics/merge-main.png
  .graphics/merge.png
  .graphics/pr-close.png
  .graphics/pr-open.png
  .graphics/schemaspy.png
  .graphics/unit-tests.png
  README.md
Labels: documentation

#1425 docs: readme reorder, adjustments
  .graphics/analysis.png
  README.md
Labels: documentation

#1426 docs: pluggable backends
  README.md
Labels: documentation

#1436 ci: integration/tests/package-lock.json
  backend/package-lock.json
  frontend/package-lock.json
  integration-tests/package-lock.json
Labels: bug

#1440 ci: clip unnecessary checkout
  .github/workflows/pr-open.yml
  database/Dockerfile
Labels: bug

#1448 feat: add timeouts to all jobs
  .github/workflows/analysis.yml
  .github/workflows/merge.yml
  .github/workflows/pr-close.yml
  .github/workflows/pr-open.yml
Labels: enhancement

#1453 update image for creating new repository
  .graphics/template.png
Labels: documentation
